"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": "newrelic-infra"
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": "deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt\
      \ bionic main"
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": |
      - |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1

        mQINBFgQ8NoBEADT59GnSBJ2Pj9AMj59JNJ7davbPrqgl5zb0JO9yfw+yU+3rCUk
        xLfdwSz8U+J7MOQ8cF3mkyIDDBfD3T1DKbAGl0Zp6cZuySSadZZJ+gMnzKiMi+5S
        nsOxzfH2q+hJ2zPEKqWgmRIDFdKoGDFp6WRLb9ce8Crg1FJ0nx/heuRiPfilwN//
        B6MLif3TjqSnD5Cyb1VN/b3UYHBfwvk3BPdIGC8w8VkrmeaXQQ+oIdxGAjbWuSdb
        yd+a0uiV1vOBgz2A7P+XCwfX5qvag87z1kMNNyAJWRSrCn8j8OdHvmLc0NsZ+Hft
        GtuieqcmD6WydaW/2rAyrlJPv+DeWV1t+YnwRLK45jstK9dCKrDMZyl/eBGnmWoa
        L7pdgQQ4AcvEbv7F7xsWM0tlJyDgzsEhubO8Ue0r/tp51JoTXiuVAS+EcVLFCuhT
        6XbGv/Gc/VLM613xi8WZGHumgtfFQvDrmYlVY3GBs4HPCyibJi6ZMtLYmRYzJYZJ
        n31c5SwN9iuNEWLxySrNGJFYnJt00JcIjvrWZF44uN8U7Byzz4RQkWCBe6sEd5L2
        TJcn/0aVQTCFn4sETzRN6GylhGuoL+eI3N0T2MRZMHKV5zBE2zwUZNV0DxqbdWWh
        mIv/QUiYfmIaPHLHhbevXKeTbMOHQyUioKZsh0l7FyArqosMOWv8hkh9kwARAQAB
        tDRpbmZyYXN0cnVjdHVyZS1lbmcgPGluZnJhc3RydWN0dXJlLWVuZ0BuZXdyZWxp
        Yy5jb20+iQI4BBMBAgAiBQJYEPDaAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIX
        gAAKCRC7Ke4DjszofMYvEACA4mZw4QGn44o9OjtoRXWry0PwxZyDb7LRFSqV/i0P
        yBo86zth3MP4+TxduxSDdoaLxB6A2fOZX25XOTcd5ILaWgVsfcIb9SiRCBmJA9aQ
        i5gNT/KzmCJeRyH52J+j1DPpz0JbadKxBfDLGmkeKBdIx3MCLIvchT8Wc+F+SaLT
        8DGj6W3m5fWKeCV62OCZqu5Lq5DjU/L1AqbbgsWI3SpeFTgTy7XnOM/ecGkrjC3M
        W+jkkhA9mU49TctWmdyFUMNQOwvdjz4BcayKZQO5ubShuYSF/J9NQnhtA9HNdLey
        CMaru6DSUHZ2DA161joNUm7eoMyXgU6tioFBPUsNG9KIL7/9o4tR3rujCehrC1ZB
        F3E5TySmucpueYg7C3HVjjyLDXy9hlu2DUr+8S7Sg1RT6gBHpp5BBxOrm9MxrNry
        QM72Pw6aVPmPeaTP5RCB7orlqfYaBsrZVww22kaQB4K9jSeCaai2NIMXWEd2i3pb
        18mFsKHrpTolzqmLvdehxtNWsE6XBJoVl0FGmtvpXwcQU/jwXvqWuOPD6Re1AvyH
        tCrWpr7AFU0T38AXszhRdnKuqFihfWVaTlWjzqOY05xLSGBrxddAz6dJF4qCopPu
        RxizNGC6dUJxuQlJfVLPJKN3EDSphCe/+FLa5PMt0U1NrLfuMdtZLWH5a9fbDwxw
        TQ==
        =uCVl
        -----END PGP PUBLIC KEY BLOCK-----
  "license_key":
    "type": "string"
    "default": ""
    "description": "New Relic Liscense Key"
